[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
remappings = [
  '@thirdweb-dev/=lib/contracts/',
  '@ds-test=lib/forge-std/lib/ds-test/src/',
  '@std=lib/forge-std/src/',
]


# See more config options https://github.com/foundry-rs/foundry/tree/master/config